package com.soujuw.android.partner.Dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig usedHouseDaoConfig;

    private final UsedHouseDao usedHouseDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        usedHouseDaoConfig = daoConfigMap.get(UsedHouseDao.class).clone();
        usedHouseDaoConfig.initIdentityScope(type);

        usedHouseDao = new UsedHouseDao(usedHouseDaoConfig, this);

        registerDao(UsedHouse.class, usedHouseDao);
    }

    public void clear() {
        usedHouseDaoConfig.getIdentityScope().clear();
    }

    public UsedHouseDao getUsedHouseDao() {
        return usedHouseDao;
    }

}
