package com.soujuw.android.partner.Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "USED_HOUSE".
 */
public class UsedHouse {

    private Long id;
    private Integer idRemote;
    private String ImageUrl;
    private String Title;
    private Integer BedRooms;
    private Integer LivingRooms;
    private String Decoration;
    private Integer Price;
    private String District;
    private String RQName;
    private Float GrossArea;
    private Integer PhotoCount;
    private Integer Floor;
    private Integer TopFloor;
    private Integer Orientation;
    private Integer BuiltYear;
    private java.util.Date LastEdit;
    private Integer BathRooms;
    private java.util.Date PublishedAt;
    private String Label1;
    private String Label2;
    private String Label3;
    private String Label4;

    public UsedHouse() {
    }

    public UsedHouse(Long id) {
        this.id = id;
    }

    public UsedHouse(Long id, Integer idRemote, String ImageUrl, String Title, Integer BedRooms, Integer LivingRooms, String Decoration, Integer Price, String District, String RQName, Float GrossArea, Integer PhotoCount, Integer Floor, Integer TopFloor, Integer Orientation, Integer BuiltYear, java.util.Date LastEdit, Integer BathRooms, java.util.Date PublishedAt, String Label1, String Label2, String Label3, String Label4) {
        this.id = id;
        this.idRemote = idRemote;
        this.ImageUrl = ImageUrl;
        this.Title = Title;
        this.BedRooms = BedRooms;
        this.LivingRooms = LivingRooms;
        this.Decoration = Decoration;
        this.Price = Price;
        this.District = District;
        this.RQName = RQName;
        this.GrossArea = GrossArea;
        this.PhotoCount = PhotoCount;
        this.Floor = Floor;
        this.TopFloor = TopFloor;
        this.Orientation = Orientation;
        this.BuiltYear = BuiltYear;
        this.LastEdit = LastEdit;
        this.BathRooms = BathRooms;
        this.PublishedAt = PublishedAt;
        this.Label1 = Label1;
        this.Label2 = Label2;
        this.Label3 = Label3;
        this.Label4 = Label4;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getIdRemote() {
        return idRemote;
    }

    public void setIdRemote(Integer idRemote) {
        this.idRemote = idRemote;
    }

    public String getImageUrl() {
        return ImageUrl;
    }

    public void setImageUrl(String ImageUrl) {
        this.ImageUrl = ImageUrl;
    }

    public String getTitle() {
        return Title;
    }

    public void setTitle(String Title) {
        this.Title = Title;
    }

    public Integer getBedRooms() {
        return BedRooms;
    }

    public void setBedRooms(Integer BedRooms) {
        this.BedRooms = BedRooms;
    }

    public Integer getLivingRooms() {
        return LivingRooms;
    }

    public void setLivingRooms(Integer LivingRooms) {
        this.LivingRooms = LivingRooms;
    }

    public String getDecoration() {
        return Decoration;
    }

    public void setDecoration(String Decoration) {
        this.Decoration = Decoration;
    }

    public Integer getPrice() {
        return Price;
    }

    public void setPrice(Integer Price) {
        this.Price = Price;
    }

    public String getDistrict() {
        return District;
    }

    public void setDistrict(String District) {
        this.District = District;
    }

    public String getRQName() {
        return RQName;
    }

    public void setRQName(String RQName) {
        this.RQName = RQName;
    }

    public Float getGrossArea() {
        return GrossArea;
    }

    public void setGrossArea(Float GrossArea) {
        this.GrossArea = GrossArea;
    }

    public Integer getPhotoCount() {
        return PhotoCount;
    }

    public void setPhotoCount(Integer PhotoCount) {
        this.PhotoCount = PhotoCount;
    }

    public Integer getFloor() {
        return Floor;
    }

    public void setFloor(Integer Floor) {
        this.Floor = Floor;
    }

    public Integer getTopFloor() {
        return TopFloor;
    }

    public void setTopFloor(Integer TopFloor) {
        this.TopFloor = TopFloor;
    }

    public Integer getOrientation() {
        return Orientation;
    }

    public void setOrientation(Integer Orientation) {
        this.Orientation = Orientation;
    }

    public Integer getBuiltYear() {
        return BuiltYear;
    }

    public void setBuiltYear(Integer BuiltYear) {
        this.BuiltYear = BuiltYear;
    }

    public java.util.Date getLastEdit() {
        return LastEdit;
    }

    public void setLastEdit(java.util.Date LastEdit) {
        this.LastEdit = LastEdit;
    }

    public Integer getBathRooms() {
        return BathRooms;
    }

    public void setBathRooms(Integer BathRooms) {
        this.BathRooms = BathRooms;
    }

    public java.util.Date getPublishedAt() {
        return PublishedAt;
    }

    public void setPublishedAt(java.util.Date PublishedAt) {
        this.PublishedAt = PublishedAt;
    }

    public String getLabel1() {
        return Label1;
    }

    public void setLabel1(String Label1) {
        this.Label1 = Label1;
    }

    public String getLabel2() {
        return Label2;
    }

    public void setLabel2(String Label2) {
        this.Label2 = Label2;
    }

    public String getLabel3() {
        return Label3;
    }

    public void setLabel3(String Label3) {
        this.Label3 = Label3;
    }

    public String getLabel4() {
        return Label4;
    }

    public void setLabel4(String Label4) {
        this.Label4 = Label4;
    }

}
